Auto stash before merge of "feat/district-turnout" and "origin/feat/district-turnout"

diff --git a/web/Dockerfile b/web/Dockerfile
--- a/web/Dockerfile
+++ b/web/Dockerfile
@@ -1,16 +1,26 @@
 FROM node:8-alpine AS base
 
+# Build arguments
+ARG PUBLIC_URL
+ARG NODE_PATH
+ARG REACT_APP_GRAPHQL_URI
+ARG REACT_APP_GA_TRACKING_ID
+ARG REACT_APP_HOST_URI
+
+# check for REACT_APP_HOST_URI. fail the build if no build argument set
+RUN if [ -z $REACT_APP_HOST_URI ]; then echo 'build arguments not set' && exit 1; fi
+
 WORKDIR /tmp
 
 # Install app dependencies
 COPY . .
 
 RUN apk add --no-cache --virtual .gyp \
-  python \
-  make \
-  g++ &&
-  npm install &&
-  apk del .gyp
+        python \
+        make \
+        g++ \
+    && npm install \
+    && apk del .gyp
 
 RUN npm run build
 
