update dockerfile and add build script

diff --git a/web/Dockerfile b/web/Dockerfile
--- a/web/Dockerfile
+++ b/web/Dockerfile
@@ -1,14 +1,32 @@
-FROM node:alpine AS base
+FROM node:8-alpine AS base
 
-WORKDIR /app
+# Build arguments
+ARG PUBLIC_URL
+ARG NODE_PATH
+ARG REACT_APP_GRAPHQL_URI
+ARG REACT_APP_GA_TRACKING_ID
+ARG REACT_APP_HOST_URI
 
-COPY ./web/package*.json /app/
+# check for REACT_APP_HOST_URI. fail the build if no build argument set
+RUN if [ -z $REACT_APP_HOST_URI ]; then echo 'build arguments not set' && exit 1; fi
+
+WORKDIR /tmp
+
+# Install app dependencies
+COPY package.json .
 
 RUN npm install
 
-COPY ./web /app/
+WORKDIR /app
 
-RUN node --max_old_space_size=4096 node_modules/.bin/react-scripts build
+RUN ls /tmp
+
+# copy production node_modules aside
+RUN cp -R /tmp/node_modules /app/node_modules
+
+COPY . .
+
+RUN npm run build
 
 FROM nginx:latest
 
